x-defaults: &common-config
  networks:
    - torrent_network
    - traefik_network
  dns:
    - 192.168.0.150
    # - 1.1.1.1
    # - 1.0.0.1
  extra_hosts:
    - "host.docker.internal:host-gateway"
  restart: unless-stopped

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    networks:
      - torrent_network
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      # - 9999:9999 # Health check
      - 8191:8191 # Flaresolverr
    healthcheck:
      test: ping -c 1 1.1.1.1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ${CONFIG_BASE_DIR}/gluetun:/gluetun
    environment:
      - TZ=${TZ}
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTONVPN_PRIVATE_KEY}
      - SERVER_COUNTRIES=Spain
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - HTTPPROXY_STEALTH=on
      - SHADOWSOCKS=on
      - SHADOWSOCKS_LOG=on
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - torrent_network
    depends_on:
      gluetun:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    <<: *common-config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_DIR}/radarr:/config
      - ${MEDIA_BASE_DIR}/Movies:/movies
      - ${MEDIA_BASE_DIR}/qbittorrent:/downloads
    ports:
      - 7878:7878
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAINNAME}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    <<: *common-config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_DIR}/sonarr:/config
      - ${MEDIA_BASE_DIR}/Series:/tvseries
      - ${MEDIA_BASE_DIR}/qbittorrent:/downloads
    ports:
      - 8989:8989
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAINNAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    <<: *common-config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAINNAME}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=cloudflare"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    <<: *common-config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_DIR}/bazarr:/config
      - ${MEDIA_BASE_DIR}/Movies:/movies #optional
      - ${MEDIA_BASE_DIR}/Series:/tvseries #optional
    ports:
      - 6767:6767
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAINNAME}`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=cloudflare"

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    <<: *common-config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_DIR}/lidarr:/config
      - ${MEDIA_BASE_DIR}/Songs:/music #optional
      - ${MEDIA_BASE_DIR}/qbittorrent:/downloads #optional
    ports:
      - 8686:8686
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAINNAME}`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.tls.certresolver=cloudflare"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    <<: *common-config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - LOG_LEVEL=debug
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_BASE_DIR}/qbittorrent:/config
      - ${MEDIA_BASE_DIR}/qbittorrent:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAINNAME}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.tls.certresolver=cloudflare"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

networks:
  torrent_network:
    name: torrent_network
    driver: bridge
  traefik_network:
    external: true
